import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import { ThemeProvider } from 'next-themes'
import ThemeSwitch from "./ThemeSwitch";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >      
        <Link
          href="/"
          className="fixed top-1 left-1 z-20 flex items-center"
          aria-label="Home"
        >
          <Image
            src="/logo.png" 
            alt="Logo"
            width={80}
            height={80}
            priority
          />
          <Image
            src="/byte.png" 
            alt="Byte Engineering"
            width={180}
            height={30}
            priority
          />
        </Link>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
