name: Node.js Build & Test Pipeline
on:
  push:
    branches: [main, dev]
  pull_request:
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' 
      - name: Install dependencies
        run: npm ci && npx next build
      - name: Lint with ESLint
        run: npm run lint
      - name: Run unit tests (Jest)
        run: npm test
      - name: Build the app
        run: npm run build
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 60
